### ISSUE TITLE
Job-making is too OP

### ISSUE THREAD

**Issue by kaborja** [Seniru/TFM_Clicker#29]
I've tried this game with two others in the tribe house, and to say the least, it was fun until one of us opened a company, then made a job paying $999999 for 1% energy and hardly any education.
It's very OP and in my opinion it would be better to change it for a more challenging gameplay.

Here are some suggestions:
- company owner only gets 10% of each worker's salary
- maximum salary for maximum education should be changed to $100 for 1% max., and $10000 for 100% max., as they are all proportional to each other
(don't hesitate to ask me to explain this point further if it's confusing)
- maximum salary should depend on the requirement of education, whereas the level plays out as a salary booster, boosting salary by (1 + level / 100)%

I'd prefer if some economics like supply and demand are involved, but then again I'm really ignorant when it comes to that stuff. I guess my suggestions are much easier to implement for now.

**Comment by Seniru** [comment]
I also noticed the same thing. The game style really changes a lot after working for a extremely high salary job (like in ur example). All of your suggestion are good 👍 . 

If you want to work on this issue, please notify me

And can you explain more about the supply and demand idea. It seems really interesting!

**Comment by Seniru** [comment]
This issue is open to discuss further information and better ideas to solve this problem

**Comment by kaborja** [comment]
I got another idea for the first two points. Instead of having 10% as the default for the company owner, he could modify this value. If he chose to get more than 10% off his worker's salary, then his worker's salary would decrease (his worker would get less than 90%) and vice-versa. This actually might encourage some strategical thinking when it comes to job-making. :)

**Comment by Seniru** [comment]
Wow! That one is great!
There should be a complete change to the game!

**Comment by Seniru** [comment]
This issue is open for anyone who is interested and can solve this issue

**Comment by Seniru** [comment]
Decided to add an investment system to the company. So if owners invest more, the job salary will be high.

**Comment by Seniru** [comment]
Work is done mostly, just need few UI improvements now.
Sorry for addressing this issue very late 🙇
