### ISSUE TITLE
Complete tips

### ISSUE THREAD

**Issue by Seniru** [Seniru/TFM_Clicker#8]
Complete tips

Tips should include
 - Help for the gameplay
 - Skills to apply in the game
 - Tricks

All the tips should include a way to navigate through each tip (An arrow for example). Create a function if possible

**Comment by Overjoy06-Creator** [comment]
Update : 
There Are Now 30 tips

**Comment by Seniru** [comment]
Resolved this issue with the commit https://github.com/Seniru/TFM_Clicker/commit/9c1cdf344624b9c7d1b35b3eeadeba8f36ed2c12.
Thanks @Overjoy06-Creator for helping!
