### ISSUE TITLE
Tip Book

### ISSUE THREAD

**Issue by Overjoy06-Creator** [Seniru/TFM_Clicker#9]
Tip Book Bug

- Page 20
-_To enable players seeing the 'Page 20' and '« »'_

**Comment by Seniru** [comment]
This issue will be solved with the issue #6 . Issue is open for ideas and suggestions for further improvements.

**Comment by Seniru** [comment]
The problem has been resolved. This change can be seen in the effects branch. Soon after it's work finished it will be merged to the master @Overjoy06-Creator

**Comment by Seniru** [comment]
@all-contributors please add @Overjoy06-Creator for findingBug, ideas, code
